// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-LzVAxaBUBGEoYRMa1nQDkXCKVH4HCkM',
    appId: '1:1067066133885:web:d55c9676e1d754f4005014',
    messagingSenderId: '1067066133885',
    projectId: 'my-jenipapo-app',
    authDomain: 'my-jenipapo-app.firebaseapp.com',
    databaseURL: 'https://my-jenipapo-app-default-rtdb.firebaseio.com',
    storageBucket: 'my-jenipapo-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNhrrh3rqf4M79GMXc8qo3MD1hay23EF0',
    appId: '1:1067066133885:android:bafe807e453efc72005014',
    messagingSenderId: '1067066133885',
    projectId: 'my-jenipapo-app',
    databaseURL: 'https://my-jenipapo-app-default-rtdb.firebaseio.com',
    storageBucket: 'my-jenipapo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXBcht5eyoMsXZn44RZSaGjqoG6u_zEoI',
    appId: '1:1067066133885:ios:38ddfa81119b6829005014',
    messagingSenderId: '1067066133885',
    projectId: 'my-jenipapo-app',
    databaseURL: 'https://my-jenipapo-app-default-rtdb.firebaseio.com',
    storageBucket: 'my-jenipapo-app.appspot.com',
    iosClientId: '1067066133885-fr97k2bi2ckskl60cli3s6ptmmlnu0mb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXBcht5eyoMsXZn44RZSaGjqoG6u_zEoI',
    appId: '1:1067066133885:ios:0ce685d2c2cf3758005014',
    messagingSenderId: '1067066133885',
    projectId: 'my-jenipapo-app',
    databaseURL: 'https://my-jenipapo-app-default-rtdb.firebaseio.com',
    storageBucket: 'my-jenipapo-app.appspot.com',
    iosClientId: '1067066133885-utm8d2mcofdjnda38b44n7c37mk70icl.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirebaseApp.RunnerTests',
  );
}
